import {Store} from './store';

export const StockTrackerCa: Store = {
  currency: '$',
  labels: {
    meta: {
      container: 'body',
      type: 'textContent',
    },
  },
  links: [
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3060',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15309513',
    },
    {
      brand: 'evga',
      model: 'xc gaming',
      series: '3060',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15318940',
    },
    {
      brand: 'asus',  
      model: 'strix oc',
      series: '3060',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15309514',
    },
    {
      brand: 'zotac',
      model: 'twin edge',
      series: '3060',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15309504',
    },
    {
      brand: 'zotac',
      model: 'twin edge oc',
      series: '3060',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15309503',
    },
    {
      brand: 'msi',
      model: 'ventus 3x',
      series: '3060',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15324508',
    },
    {
      brand: 'msi',
      model: 'ventus 2x oc',
      series: '3060',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15317226',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra',
      series: '3060ti',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15229237',
    },
    {
      brand: 'nvidia',
      model: 'founders edition',
      series: '3060ti',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15166285',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3060ti',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15201200  ',
    },
    {
      brand: 'msi',
      model: 'ventus 2x oc',
      series: '3060ti',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15178453',
    },
    {
      brand: 'nvidia',
      model: 'founders edition',
      series: '3070',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15078017',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15147122',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3070',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15053087',
    },
    {
      brand: 'asus',
      model: 'dual oc',
      series: '3070',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15053086',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3070',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15053085',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3070',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15038016',
    },
    {
      brand: 'zotac',
      model: 'twin edge',
      series: '3070',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15000079',
    },
    {
      brand: 'zotac',
      model: 'twin edge oc',
      series: '3070',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15000078',
    },
    {
      brand: 'zotac',
      model: 'twin edge oc white',
      series: '3070',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15223142',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3080',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15084753',
    },
    {
      brand: 'zotac',
      model: 'trinity',
      series: '3080',
      url: 'https://stocktrack.ca/bb/availability.php?sku=14953249',
    },
    {
      brand: 'msi',
      model: 'ventus 3x',
      series: '3080',
      url: 'https://stocktrack.ca/bb/availability.php?sku=14950588',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3080',
      url: 'https://stocktrack.ca/bb/availability.php?sku=14953248',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3080',
      url: 'https://stocktrack.ca/bb/availability.php?sku=14954116',
    },
    {
      brand: 'zotac',
      model: 'trinity oc',
      series: '3080',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15000077',
    },
    {
      brand: 'zotac',
      model: 'trinity',
      series: '3090',
      url: 'https://stocktrack.ca/bb/availability.php?sku=14953250',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3090',
      url: 'https://stocktrack.ca/bb/availability.php?sku=14953247',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3090',
      url: 'https://stocktrack.ca/bb/availability.php?sku=14954117',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3090',
      url: 'https://stocktrack.ca/bb/availability.php?sku=14966477',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3090',
      url: 'https://stocktrack.ca/bb/availability.php?sku=14967857',
    },
    {
      brand: 'sony',
      model: 'ps5 console',
      series: 'sonyps5c',
      url: 'https://stocktrack.ca/bb/availability.php?sku=14962185',
    },
    {
      brand: 'sony',
      model: 'ps5 digital',
      series: 'sonyps5de',
      url: 'https://stocktrack.ca/bb/availability.php?sku=14962184',
    },
    {
      brand: 'microsoft',
      model: 'xbox series x',
      series: 'xboxsx',
      url: 'https://stocktrack.ca/bb/availability.php?sku=14964951',
    },
    {
      brand: 'microsoft',
      model: 'xbox series s',
      series: 'xboxss',
      url: 'https://stocktrack.ca/bb/availability.php?sku=14964950',
    },
    {
      brand: 'amd',
      model: '5600x',
      series: 'ryzen5600',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15331713',
    },
    {
      brand: 'amd',
      model: '5800x',
      series: 'ryzen5800',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15331715',
    },
    {
      brand: 'amd',
      model: '5900x',
      series: 'ryzen5900',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15331714',
    },
    {
      brand: 'amd',
      model: '5950x',
      series: 'ryzen5950',
      url: 'https://stocktrack.ca/bb/availability.php?sku=15331716',
    },
  ],
  name: 'stocktracker-ca',
  waitUntil: 'domcontentloaded',
};
